### ISSUE TITLE
Провести встречу + определить цели и задачи по проекту

### ISSUE THREAD

**Issue by vkamiansky** [hypnospinner/ToDo#10]
Предлагаемая дата 10 ноября (уточнить)
Место: Петергоф (уточнить)

Предварительная подготовка: книги см #8 + желательно: 
 - DDD:  Domain Modeling Made Functional (основы DDD, но следует сразу воспринимать материал  без привязки ООП или другой конкретной парадигме. Понимать суть подхода.)
 - дизайн форм: изучить Blend

Средства разработки: Visual Studio 2017 Community + Xamarin Forms + Blend; VS Code; SourceTree.

**Comment by hypnospinner** [comment]
### Встреча
Дата: 10 ноября подходит нам всем - пар (везение) ни у кого нет.
Место: Петергоф хоть и красив, но толковых мест для переговором (разве что шавушечных) там нет, поэтому было бы лучше в городе (центре или юге). Место в городе уже не так принципиально.

### Знания
1. DDD на первый взгляд кажется довольно сложной и непонятной штукой, особенно для любей которые не сталкивались с подобными предметно-ориентированными задачами. Если вы можете подкинуть какие-то ресурсы буквально для чайников - я буду очень благодарен. Плюс я все таки больше тяготяею к ООП чем функционалке, поэтому подход кажется мне совсем уж страшным и непонятным ( я заранее извиняюсь за глупые вопросы по этой теме)
2. Т.к. Blend на начальных этапах (ИМХО) не будет принципиально важен, то я отложил его всторону, но как тулзу для создания UI оценил, понял, принял.
3. У нас появились некоторые мысли касательно функционала, всвязи с чем возникла мысль сделать какой-нибудь гугл-док для сбора, обощения, обсуждения и кокретизации всяких фич. Мысли о своего рода мотивации пользователя к свершениям со стороны приложения

**Comment by vkamiansky** [comment]
Отлично! Если в Питере, предлагаю встретиться в Кофестории https://vk.com/kofestoria . Лучше места в городе для такого формата встречи имхо не найти. Могу вас встретить у метро на машине.

1.  Не нужно сосредотачиваться на парадигме (ООП или ФП). Про ООП и ФП и их применение, можно послушать мой доклад https://github.com/vkamiansky/case.study-oop.fp.balance )). Рекомендую. В этом репозитории и ссылка на видео и доп. статьи и заметки по теме и ссылки на разные материалы и книги. DDD про процесс построения приложения от предметной области. Нужно вытащить оттуда максимум идей, притворившись, что ничего не знаешь про ООП или ФП. 

2.  Blend для дизайна интерфейса. Тот, кто будет заниматься слоем представления, может быть очень эффективен, используя этот инструмент. В контексте разработки приложения это будет не менее важно, чем навыки проектирования логики.
 
3. Если есть мысли, почему не формулировать их здесь в виде issues? Но я бы всё таки глубже заглянул в то, какую цель мы ставим. Нужны ли свершения вообще? Если да, то почему и в каком виде? Как облегчить решение задач пользователя, а не усложнить их? Сначала нужно прийти к пониманию того, чем наш подход будет радикально полезнее для нас самих, чем всё, что уже сделано до нас. Для этого и нужно встретиться. На этом этапе будет очень интенсивное обсуждение, и вести его в формате текста может оказаться неэффективным. 

Самое важное: мы отправляемся в путешествие к границе (а потом за границу) наших умственных возможностей. Цель путешествия - получить приложение, которое облегчит нам решение задач минимум в 2 раза, научиться проектировать и разрабатывать приложения на уровне немыслимом для нас сейчас и ещё чуть лучше, стать экспертами в предметной области стратегии, тактики и масштабировании при решении задач.

Чего из опыта предлагаю категорически опасаться: 1) стать фанатами конкретной технологии, парадигмы, практики (!!!), 2) мышления "куда применить мои знания?" вместо "что узнать чтобы решить бизнес-задачу?"(!!!) 3) бояться высказывать свои опасения или идеи, бояться негативной оценки, бояться показаться идиотом. 

Вот такие мои предложения) Приветствую критику. По поводу места встречи жду подтверждения или альтернативной идеи.

**Comment by vkamiansky** [comment]
@hypnospinner добавляй меня в контрибьютеры ;)

**Comment by hypnospinner** [comment]
С датой встречи мы разобрались, давайте разберемся со временем.
Я пока спрашиваю у ребят. Лично мне было бы удобнее либо утром, либо днем-вечером, но девочкам ехать из Петергофа, это ~полтора часа до Автово, так что скорее всего второе.

**Comment by vkamiansky** [comment]
Как насчёт встретиться в 14:30? Предлагайте, пожалуйста, также место. Мы можем встретиться у Финляндского вокзала?

**Comment by hypnospinner** [comment]
Тут мы так прикинули, что встретится в 12 (~11:30 на балтийскую приедет электричка) нам было бы удобнее. Если вы можете - отлично.

**Comment by hypnospinner** [comment]
И сколько времени примерно займет встреча?

**Comment by vkamiansky** [comment]
Я могу. Предлагаю - на ты. Полагаю, встреча должна занять не больше 2 - 2.5 часов. Нужно попробовать очень интенсивно поработать.

**Comment by hypnospinner** [comment]
Отлично! Есть смысл брать ноуты?

**Comment by hypnospinner** [comment]
А мы встречаемся в кофестории которая на охоте или на техноложке?

**Comment by vkamiansky** [comment]
https://wbd.ms/share/v2/aHR0cHM6Ly93aGl0ZWJvYXJkLm1pY3Jvc29mdC5jb20vYXBpL3YxLjAvd2hpdGVib2FyZHMvcmVkZWVtLzZmMDM5YmI0N2Q3OTRiMGJiNzQxZjZhMzFlZTIxNTBlX0JCQTcxNzYyLTEyRTAtNDJFMS1CMzI0LTVCMTMxRjQyNEUzRA==

**Comment by vkamiansky** [comment]
![whiteboard](https://user-images.githubusercontent.com/6636792/48303827-a2551800-e520-11e8-8649-8c91f8f2bb51.png)
