### ISSUE TITLE
Определить список возможностей (feature) приложения

### ISSUE THREAD

**Issue by vkamiansky** [hypnospinner/ToDo#12]
1) Необходимо определить общий список возможностей, которые на данном уровне понимания мы вообще хотим видеть в приложении. За основу можно взять список по результатам встречи #10 .

2) Дать оценки каждой возможности по след. принципу: * -> обязательно хочу уже в первом релизе , 1-5 -> насколько это представляется важным именно мне? (важность) (5 - очень важно), a-e ->  насколько часто я буду пользоваться этой возможностью? (востребованность) (а - очень часто), 

3) Цель приложения - тактический успех пользователя.
    * не тратить время на то, что не относится к работе, когда есть время для работы
    * не тратить время на то, что не относится к описанию проблемы, когда она обнаружилась
    * не тратить время на то, что не относится к описанию решения, когда оно пришло в голову

     Дать оценки, насколько та или иная возможность отвечает целям приложения (полезность). (+, ++, +++).

3) Отсортировать возможности приложения по убыванию важности, востребованности и полезности.

4) Выбрать все со звёздочками  + 3 самые топовые без звёздочек. Они войдут в первый релиз.

**Comment by hypnospinner** [comment]
Я поразмыслил и понял, что мы отошли от начальной идеи. 
Я видел ее в том, что приложение помогает сфокусировать внимание пользователя на задаче, не раздражая его громоздким и демотивирующим интерфейсом из тысяч task'ов и их списков, предлагая пользователю возможность просто сосредоточится на чем-то, и сразу же за него взяться. Эдакий "Just Do It" мира task-list'ов.
Тот feature-list, который мы сформулировали на встрече и продолжаем расширять, превращает его в приложение-конструктор, которое пытается усидеть на 10 стульях одновременно. Несомненно люди разные и им нужны разные способы организации своего труда, но дельта этих отличий может быть настолько большой, что каким бы гибким приложение не было и сколько расширений оно бы не предлагало, оно не сможет помочь всем. Я не уверен, что вообще можно сделать такое приложение, которое сможет стать удобным для всех. В нем придется продумать очень много мелочей. Например: изначально оно должно быть настроено так, чтобы пользователь, который меньше всего хочет лезть в настрйки, получил все то, что ему нужно (и желательно вовсе не лез в Settings). 
Кол-во абстрактных мыслей настолько подавляет структурированность, поэтому я предложу некторую схему того, как это все сейчас sum up'нуть.

### Pipeline идейного создания
Для кого наш проект? => С каким проблемами сталкивается target user? => Как приложение помогает их решать (что вытекает в features приложения)

**Для кого наше приложение?**
Для тех, кто не хочет тратить время на долгий выбор задачи среди множества списков

**С какими проблемами сталкивается target user?**
- Страх большого объема задач
- Плохая структурированность задач
- Плохая приоритезация задач
- Привычка постоянно переключаться между несколькими делами одновременно
- Отсутствие мотивации что-то делать, т.к. оно требует абстрактного решения о том, что делать (которое не приносит видимого рещультата для "раскачки")

**Как приложение их решает?**
1. Страх большого объема задач: 
- сокрытие задачи от пользователя, которое легко обходится переходом к списку задач
2. Плохая структурированность задач:
- гибкий pipeline создания задачи (с удобным и понятным интерфейсом, который сосредотачивает на одной из граней настройки проблемы за раз); 
- разбиение на задачи и решения
- создание глобальных (стратегических) проблем
- создание JIT (just-in-time, тактических)  проблем
- привязка проблемы к классу проблем => класс проблем как фича
- беззадачные решения
...

Думаю на этом этапе идея ясна
Предлагаю для этого исользовать Google Drive. Я сделала [папку](https://drive.google.com/drive/folders/1oLoKVoSmRR6JmeKv3GdWMisApxDlh60a?usp=sharing) для разных фаилов по проекту (схем, таблиц, доков и т.д.)
Если мы собираемся все-таки строить приложение по принципу "Everything is feature", то я думаю этот pipeline тоже подойдет.

**Comment by vkamiansky** [comment]
Отлично! Предлагаю до вторника определиться с фичами, и начать делать скетчи экранов. Я постараюсь внести свои добавления в гугл-таблицу сегодня вечером.

**Comment by hypnospinner** [comment]
Я добавил колонки для оценок фич в таблице. В заголовке есть комментарий, но вот еще раз пояснение:

 - "-1" - против фичи
 - "0" - нейтрально
 - "1" - за фичу в будущем
 - "2" - за фичу в первой версии

Я все таки в большей степени за приложение, ориентированное на фокусировке внимания пользователя на задаче, а не сервиса по строительству своего task manager. Очевдно, что первое реализуемо в рамках второго и тогда нужно заранее продумывать приложение так, чтобы оно работало именно по принципу _everything is feature_ и создавать конфигурации "из коробки" опять таки в настройках

**Comment by vkamiansky** [comment]
Протокол оценки от Ильи очень практичный. Большая просьба всем расставить оценки с крайним сроком в пятницу. Я свои уже расставил) В качестве рекомендации: перед выставлением оценок лучше колонки с оценками других участников схлопнуть, чтобы исключить их влияние.

**Comment by hypnospinner** [comment]
### Об интерфейсе и создании задач

Отмечу одну мысль касательно удобства использования разных to-do list'ов.
Очень часто (лично мне) неудобно создавать новые задачи. Мне сразу предоставляют слишком много разных полей, которые часто очень неудобно использовать и заметить. Например:

![image](https://user-images.githubusercontent.com/40162026/48640141-c87a2c80-e9e6-11e8-94c0-f301117c8e50.png)

_Microsoft To-Do_

Проблема этого интерфеса в том, что под дело выделенно слишком мало места относительно всего простарнства (это освсем не про сосредоточение на конкретной задаче). Лично мне также не нравится, что есть пустые поля с дедлайном, напоминаниями, описанием, которые ровно так же мешают при создании дела.

### Принципы создания задач _(общая идея подойдет и для решений)_
**1. Пользователь не получает слишком много настроек за раз**
т.е. нужно делать разбиение конкретных настроек (дедлайна, напоминания, описания, под-задач и т.д.) на разные экраны, например для дедлайнов можно сразу выдавать календарь, где можно просто взять и сразу выбрать даты (+кнопка пропустить пункт)
**2. Пользователь видит только то, что относится к задаче**
т.е если user не добавлял дедлайн, данных о дедлайне и не будет, но его всегда можно будет добавить, нажав на кнопку редактирования задачи 
**3. Создание задачи разбито на этапы**
это логическое расширения и пояснение к первому пункту. Создавая задачу, пользователь свайпом или нажатием на кнопку переходит от настрйки к настройке (или сразу нажимает на кнопку завершить создание), где он пишет название задачи, добавляет под-задачи, collaborators, описание, дедлайн, напоминание, решение, важность, progress bar и пр. Конечно, в любой момент можно остановаиться и завершить создание.

_Возможно есть смысл в создании шаблонов задач, что может упростить задачу для некоторых ползователей_

**Микро-вывод/идея**
Пока я все это писал, подумалось, что было бы неплохо оценивать интерфейс с точки зрения кол-ва нажатий/действий которые должен совершить ползователь и пришел вот к токому филосовскому принципу приложения (который и предлагаю включить)

> **_Минимум нажатий - максимум дел_**

**Comment by vkamiansky** [comment]
@hypnospinner я добавил страницу в вики [философия проекта](https://github.com/hypnospinner/ToDo/wiki/Philosophy). Те идеи, которые должны сохраниться после решения той или иной тактической проблемы и закрытия соответствующей issue, следует помещать на новую страницу вики со ссылкой на новый материал на главной странице вики.

**Comment by vkamiansky** [comment]
Огромное спасибо всем, кто голосовал! Теперь время подвести итоги голосования #14, а также определиться с названием проекта #13. Отдельное спасибо @hypnospinner за практичную систему оценок.
