### ISSUE TITLE
Придумать название для проекта

### ISSUE THREAD

**Issue by hypnospinner** [hypnospinner/ToDo#13]
TODOша явно себя изжила. Нужно придумать что-то новое, обыгрывающее основную идею приложения (но тут нужно обсудить так же основные вопросы для проекта #12 ).
Т.к. я пока вижу приложение не столько task-list'ом, а скольок task-focuser'ом, я предлагаю 2 идеи:
- Redoer [ПЕРЕсмотры концепции task-list'а]
- Focuser/Focusit [Непосредственно то, что предлагает приложение пользователю]

**Comment by SabinaAlieva** [comment]
AntiToDoList
AllToDo
AllBeDone\AllToBeDone Я неграмотная
Extradoer

**Comment by vkamiansky** [comment]
Genius Moments
Work Smart

**Comment by vkamiansky** [comment]
Creative Tactics

**Comment by vkamiansky** [comment]
Вопрос с названием проекта обязательно должен быть решён в рамках milestone 0 перед запуском milestone 1 (groundwork) и началом выполнения #15. Название должно быть звучным, легко запоминаться и отражать сущность проекта. Мой выбор - Creative Tactics. Жду ваших комментариев.

**Comment by hypnospinner** [comment]
Есть еще одна идея: Tactit, Tactlist (созвучно с tactless, что плохо, поэтому скорее первое)

**Comment by vkamiansky** [comment]
Tactit по-английски звучит ещё глупее. tac-tit это как tic-tac-toe и tit-for-tat в одном флаконе. никаких особенных положительных эмоций не вызывает. думаем дальше, включаем режим турбо. Название не обязательно должно быть коротким. Оно должно быть произносимым и запоминающимся. Выдуманные короткие слова плохи тем, что их невозможно запомнить, они ни с чем в памяти человека изначально не связаны.

**Comment by hypnospinner** [comment]
Я скорее склоняюсь к AllToDo

**Comment by vkamiansky** [comment]
Но мы же как раз от этого и уходили)
Тогда TacticList или FocusList от Focus + ToDo List.
Мне сначала даже понравился AntiToDoList, но длинновато. UnToDoList - та же проблема. Больше двух слов - слишком длинно.
Как например Focus List?
